// <auto-generated />
namespace Warehouse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class db_updt_invoice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db_updt_invoice));
        
        string IMigrationMetadata.Id
        {
            get { return "201804241920531_db_updt_invoice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
